name: cimbar_scanner
description: CimBar scanner â€” decode Color Icon Matrix Barcodes via camera or file import.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  file_picker: ^8.0.3
  share_handler: ^0.0.21
  image: ^4.2.0
  pointycastle: ^3.9.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  url_launcher: ^6.2.5
  image_picker: ^1.1.2
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.3.5

flutter:
  generate: true
  uses-material-design: true
